from pathlib import Path

from setuptools import find_packages, setup

BASEDIR = Path(__file__).parent

setup(
    name='vcd-parser',
    version='0.0.2',
    description='A parser for Value Change Dump (VCD) files (generated by PulseView)',
    long_description=(BASEDIR/'README.md').read_text(),
    long_description_content_type="text/markdown",
#   url='',
    author='Branislav Pilnan',
    author_email='b.pilnan@gmail.com',
    license='MIT',
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering",
        "Topic :: Software Development :: Embedded Systems",
        "Topic :: Utilities",
    ],
    packages=find_packages(exclude=('tests',)),
    include_package_data=True,
    install_requires=(BASEDIR/'requirements.txt').read_text().splitlines(),
    zip_safe=False
)
