from setuptools import find_packages, setup

setup(name='vcd_parser',
      version='0.0.1',
      description='A parser for Value Change Dump (VCD) files (generated by PulseView)',
    #   url='',
      author='Branislav Pilnan',
      author_email='b.pilnan@gmail.com',
    #   license='MIT',
      packages=find_packages(),
      install_requires=['python-dateutil'],
      zip_safe=False)
